<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\shared\SharedKernel\SharedKernel.csproj" />
      <ProjectReference Include="..\SceneDesign.Application\SceneDesign.Application.csproj" />
      <ProjectReference Include="..\SceneDesign.Domain\SceneDesign.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
      <PackageReference Include="MassTransit" Version="8.5.9" />
      <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.9" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.8" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    </ItemGroup>

</Project>
