// <auto-generated />
using System;
using AssetCatalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssetCatalog.Infrastructure.Migrations
{
    [DbContext(typeof(AssetCatalogDbContext))]
    [Migration("20260515162648_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("asset_catalog")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssetCatalog.Domain.Entities.AssetTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean")
                        .HasColumnName("is_custom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_asset_templates");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_asset_templates_category");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_asset_templates_name");

                    b.ToTable("AssetTemplates", "asset_catalog");
                });

            modelBuilder.Entity("AssetCatalog.Domain.Entities.AssetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_template_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_asset_versions");

                    b.HasIndex("AssetTemplateId")
                        .HasDatabaseName("ix_asset_versions_asset_template_id");

                    b.ToTable("AssetVersions", "asset_catalog");
                });

            modelBuilder.Entity("AssetCatalog.Domain.Entities.AssetTemplate", b =>
                {
                    b.OwnsOne("AssetCatalog.Domain.ValueObjects.TopographicSymbol", "TopographicSymbol", b1 =>
                        {
                            b1.Property<Guid>("AssetTemplateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Topographic_Symbol_Color");

                            b1.Property<double>("Size")
                                .HasColumnType("double precision")
                                .HasColumnName("Topographic_Symbol_Size");

                            b1.Property<string>("SymbolType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Topographic_Symbol_Type");

                            b1.HasKey("AssetTemplateId");

                            b1.ToTable("AssetTemplates", "asset_catalog");

                            b1.WithOwner()
                                .HasForeignKey("AssetTemplateId")
                                .HasConstraintName("fk_asset_templates_asset_templates_id");
                        });

                    b.Navigation("TopographicSymbol");
                });

            modelBuilder.Entity("AssetCatalog.Domain.Entities.AssetVersion", b =>
                {
                    b.HasOne("AssetCatalog.Domain.Entities.AssetTemplate", null)
                        .WithMany("Versions")
                        .HasForeignKey("AssetTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_asset_versions_asset_templates_asset_template_id");

                    b.OwnsOne("AssetCatalog.Domain.ValueObjects.ModelData", "Model", b1 =>
                        {
                            b1.Property<Guid>("AssetVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Model_File_Name");

                            b1.Property<long>("FileSize")
                                .HasColumnType("bigint")
                                .HasColumnName("Model_File_Size");

                            b1.Property<string>("FileUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Model_File_Url");

                            b1.Property<string>("Format")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Model_Format");

                            b1.Property<int>("PolygonCount")
                                .HasColumnType("integer")
                                .HasColumnName("Model_Polygon_Count");

                            b1.HasKey("AssetVersionId");

                            b1.ToTable("AssetVersions", "asset_catalog");

                            b1.WithOwner()
                                .HasForeignKey("AssetVersionId")
                                .HasConstraintName("fk_asset_versions_asset_versions_id");

                            b1.OwnsOne("AssetCatalog.Domain.ValueObjects.Dimensions", "Dimensions", b2 =>
                                {
                                    b2.Property<Guid>("ModelDataAssetVersionId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<double>("Depth")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Model_Depth");

                                    b2.Property<double>("Height")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Model_Height");

                                    b2.Property<double>("Width")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Model_Width");

                                    b2.HasKey("ModelDataAssetVersionId");

                                    b2.ToTable("AssetVersions", "asset_catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("ModelDataAssetVersionId")
                                        .HasConstraintName("fk_asset_versions_asset_versions_id");
                                });

                            b1.Navigation("Dimensions")
                                .IsRequired();
                        });

                    b.Navigation("Model")
                        .IsRequired();
                });

            modelBuilder.Entity("AssetCatalog.Domain.Entities.AssetTemplate", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
