// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectManagement.Infrastructure.Persistence;

#nullable disable

namespace ProjectManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectManagementDbContext))]
    [Migration("20260515072502_InitialProjectManagement")]
    partial class InitialProjectManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("project_management")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_projects_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_projects_status");

                    b.ToTable("Projects", "project_management");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.ProjectInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("invite_code");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_project_invitations");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_project_invitations_expires_at");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("ix_project_invitations_invite_code");

                    b.HasIndex("IsUsed")
                        .HasDatabaseName("ix_project_invitations_is_used");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_invitations_project_id");

                    b.ToTable("ProjectInvitations", "project_management");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_project_members");

                    b.HasIndex("JoinedAt")
                        .HasDatabaseName("ix_project_members_joined_at");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_project_members_member_id");

                    b.HasIndex("ProjectId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_members_project_id_member_id");

                    b.ToTable("ProjectMembers", "project_management");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Project", b =>
                {
                    b.OwnsOne("ProjectManagement.Domain.ValueObjects.ProjectSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("AllowPublicComments")
                                .HasColumnType("boolean")
                                .HasColumnName("Allow_Public_Comments");

                            b1.Property<int>("DefaultAccessLevel")
                                .HasColumnType("integer")
                                .HasColumnName("Default_Access_Level");

                            b1.Property<long>("InvitationValidityPeriod")
                                .HasColumnType("bigint")
                                .HasColumnName("Invitation_Validity_Period");

                            b1.Property<bool>("IsPublic")
                                .HasColumnType("boolean")
                                .HasColumnName("Is_Public");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects", "project_management");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId")
                                .HasConstraintName("fk_projects_projects_id");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.ProjectInvitation", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.Project", null)
                        .WithMany("Invitations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_invitations_projects_project_id");

                    b.OwnsOne("ProjectManagement.Domain.ValueObjects.ProjectRole", "SuggestedRole", b1 =>
                        {
                            b1.Property<Guid>("ProjectInvitationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Level")
                                .HasColumnType("integer")
                                .HasColumnName("Suggested_Role_Level");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Suggested_Role_Name");

                            b1.HasKey("ProjectInvitationId");

                            b1.ToTable("ProjectInvitations", "project_management");

                            b1.WithOwner()
                                .HasForeignKey("ProjectInvitationId")
                                .HasConstraintName("fk_project_invitations_project_invitations_id");
                        });

                    b.Navigation("SuggestedRole")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.Project", null)
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_project_id");

                    b.OwnsOne("ProjectManagement.Domain.ValueObjects.ProjectRole", "Role", b1 =>
                        {
                            b1.Property<Guid>("ProjectMemberId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Level")
                                .HasColumnType("integer")
                                .HasColumnName("Role_Level");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Role_Name");

                            b1.HasKey("ProjectMemberId");

                            b1.HasIndex("Level")
                                .HasDatabaseName("IX_ProjectMembers_RoleLevel");

                            b1.ToTable("ProjectMembers", "project_management");

                            b1.WithOwner()
                                .HasForeignKey("ProjectMemberId")
                                .HasConstraintName("fk_project_members_project_members_id");
                        });

                    b.Navigation("Role")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Project", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
