// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SceneDesign.Infrastructure.Persistence;

#nullable disable

namespace SceneDesign.Infrastructure.Migrations
{
    [DbContext(typeof(SceneDesignDbContext))]
    [Migration("20260515162501_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scene_design")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SceneDesign.Domain.Entities.ObjectLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_id");

                    b.HasKey("Id")
                        .HasName("pk_object_layers");

                    b.HasIndex("SceneId")
                        .HasDatabaseName("ix_object_layers_scene_id");

                    b.ToTable("ObjectLayers", "scene_design");
                });

            modelBuilder.Entity("SceneDesign.Domain.Entities.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentViewMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_view_mode");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_scenes");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_scenes_project_id");

                    b.ToTable("Scenes", "scene_design");
                });

            modelBuilder.Entity("SceneDesign.Domain.Entities.SceneObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("LayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("layer_id");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_id");

                    b.HasKey("Id")
                        .HasName("pk_scene_objects");

                    b.HasIndex("SceneId")
                        .HasDatabaseName("ix_scene_objects_scene_id");

                    b.ToTable("SceneObjects", "scene_design");
                });

            modelBuilder.Entity("SceneDesign.Domain.Entities.ObjectLayer", b =>
                {
                    b.HasOne("SceneDesign.Domain.Entities.Scene", null)
                        .WithMany("Layers")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_object_layers_scenes_scene_id");
                });

            modelBuilder.Entity("SceneDesign.Domain.Entities.Scene", b =>
                {
                    b.OwnsOne("SceneDesign.Domain.ValueObjects.SceneSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("SceneId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("DetectCollisions")
                                .HasColumnType("boolean")
                                .HasColumnName("Detect_Collisions");

                            b1.Property<int>("MaxObjectLimit")
                                .HasColumnType("integer")
                                .HasColumnName("Max_Object_Limit");

                            b1.HasKey("SceneId");

                            b1.ToTable("Scenes", "scene_design");

                            b1.WithOwner()
                                .HasForeignKey("SceneId")
                                .HasConstraintName("fk_scenes_scenes_id");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("SceneDesign.Domain.Entities.SceneObject", b =>
                {
                    b.HasOne("SceneDesign.Domain.Entities.Scene", null)
                        .WithMany("Objects")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_scene_objects_scenes_scene_id");

                    b.OwnsOne("SceneDesign.Domain.ValueObjects.Position3D", "Position", b1 =>
                        {
                            b1.Property<Guid>("SceneObjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("Position_X");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("Position_Y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("Position_Z");

                            b1.HasKey("SceneObjectId");

                            b1.ToTable("SceneObjects", "scene_design");

                            b1.WithOwner()
                                .HasForeignKey("SceneObjectId")
                                .HasConstraintName("fk_scene_objects_scene_objects_id");
                        });

                    b.OwnsOne("SceneDesign.Domain.ValueObjects.BoundingBox", "BoundingBox", b1 =>
                        {
                            b1.Property<Guid>("SceneObjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.HasKey("SceneObjectId");

                            b1.ToTable("SceneObjects", "scene_design");

                            b1.WithOwner()
                                .HasForeignKey("SceneObjectId")
                                .HasConstraintName("fk_scene_objects_scene_objects_id");

                            b1.OwnsOne("SceneDesign.Domain.ValueObjects.Position3D", "Max", b2 =>
                                {
                                    b2.Property<Guid>("BoundingBoxSceneObjectId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<double>("X")
                                        .HasColumnType("double precision")
                                        .HasColumnName("BoundingBox_Max_X");

                                    b2.Property<double>("Y")
                                        .HasColumnType("double precision")
                                        .HasColumnName("BoundingBox_Max_Y");

                                    b2.Property<double>("Z")
                                        .HasColumnType("double precision")
                                        .HasColumnName("BoundingBox_Max_Z");

                                    b2.HasKey("BoundingBoxSceneObjectId");

                                    b2.ToTable("SceneObjects", "scene_design");

                                    b2.WithOwner()
                                        .HasForeignKey("BoundingBoxSceneObjectId")
                                        .HasConstraintName("fk_scene_objects_scene_objects_id");
                                });

                            b1.OwnsOne("SceneDesign.Domain.ValueObjects.Position3D", "Min", b2 =>
                                {
                                    b2.Property<Guid>("BoundingBoxSceneObjectId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<double>("X")
                                        .HasColumnType("double precision")
                                        .HasColumnName("BoundingBox_Min_X");

                                    b2.Property<double>("Y")
                                        .HasColumnType("double precision")
                                        .HasColumnName("BoundingBox_Min_Y");

                                    b2.Property<double>("Z")
                                        .HasColumnType("double precision")
                                        .HasColumnName("BoundingBox_Min_Z");

                                    b2.HasKey("BoundingBoxSceneObjectId");

                                    b2.ToTable("SceneObjects", "scene_design");

                                    b2.WithOwner()
                                        .HasForeignKey("BoundingBoxSceneObjectId")
                                        .HasConstraintName("fk_scene_objects_scene_objects_id");
                                });

                            b1.Navigation("Max")
                                .IsRequired();

                            b1.Navigation("Min")
                                .IsRequired();
                        });

                    b.OwnsOne("SceneDesign.Domain.ValueObjects.Rotation", "Rotation", b1 =>
                        {
                            b1.Property<Guid>("SceneObjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Pitch")
                                .HasColumnType("double precision")
                                .HasColumnName("Rotation_Pitch");

                            b1.Property<double>("Roll")
                                .HasColumnType("double precision")
                                .HasColumnName("Rotation_Roll");

                            b1.Property<double>("Yaw")
                                .HasColumnType("double precision")
                                .HasColumnName("Rotation_Yaw");

                            b1.HasKey("SceneObjectId");

                            b1.ToTable("SceneObjects", "scene_design", t =>
                                {
                                    t.Property("Pitch")
                                        .HasColumnName("rotation_Pitch");

                                    t.Property("Roll")
                                        .HasColumnName("rotation_Roll");

                                    t.Property("Yaw")
                                        .HasColumnName("rotation_Yaw");
                                });

                            b1.WithOwner()
                                .HasForeignKey("SceneObjectId")
                                .HasConstraintName("fk_scene_objects_scene_objects_id");
                        });

                    b.OwnsOne("SceneDesign.Domain.ValueObjects.Scale", "Scale", b1 =>
                        {
                            b1.Property<Guid>("SceneObjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("Scale_X");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("Scale_Y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("Scale_Z");

                            b1.HasKey("SceneObjectId");

                            b1.ToTable("SceneObjects", "scene_design", t =>
                                {
                                    t.Property("X")
                                        .HasColumnName("scale_X");

                                    t.Property("Y")
                                        .HasColumnName("scale_Y");

                                    t.Property("Z")
                                        .HasColumnName("scale_Z");
                                });

                            b1.WithOwner()
                                .HasForeignKey("SceneObjectId")
                                .HasConstraintName("fk_scene_objects_scene_objects_id");
                        });

                    b.Navigation("BoundingBox")
                        .IsRequired();

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("Rotation")
                        .IsRequired();

                    b.Navigation("Scale")
                        .IsRequired();
                });

            modelBuilder.Entity("SceneDesign.Domain.Entities.Scene", b =>
                {
                    b.Navigation("Layers");

                    b.Navigation("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
